"""empty message

Revision ID: 22fb3c9fa079
Revises: 
Create Date: 2023-01-31 16:14:48.370165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fb3c9fa079'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operator_login'), ['login'], unique=True)
        batch_op.create_index(batch_op.f('ix_operator_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operator_phone'))
        batch_op.drop_index(batch_op.f('ix_operator_login'))

    op.drop_table('operator')
    # ### end Alembic commands ###
