"""brigade, emploees, brigade

Revision ID: 759f2b5ee076
Revises: 22fb3c9fa079
Create Date: 2023-01-31 21:10:11.230648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759f2b5ee076'
down_revision = '22fb3c9fa079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(length=64), nullable=False),
    sa.Column('house', sa.Integer(), nullable=False),
    sa.Column('frame', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=False),
    sa.Column('longitude', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brigade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brigade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brigade_name'), ['name'], unique=True)

    op.create_table('employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('brigade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brigade_id'], ['brigade.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_phone'))

    op.drop_table('employee')
    with op.batch_alter_table('brigade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brigade_name'))

    op.drop_table('brigade')
    op.drop_table('address')
    # ### end Alembic commands ###
