"""client

Revision ID: d583e99e5235
Revises: 759f2b5ee076
Create Date: 2023-01-31 21:54:01.672291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd583e99e5235'
down_revision = '759f2b5ee076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_phone'), ['phone'], unique=True)

    op.create_table('entity',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name_of_company', sa.String(length=64), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('phys',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_longitude'), ['longitude'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_longitude'))
        batch_op.drop_index(batch_op.f('ix_address_latitude'))

    op.drop_table('phys')
    op.drop_table('entity')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_phone'))

    op.drop_table('client')
    # ### end Alembic commands ###
